### ISSUE TITLE
Reinitialize/clear the delay(timeout) time on tab change

### ISSUE THREAD

**Issue by knitevision1** [vdw/Tabslet#17]
When you have ``autorotate`` and, like, ``delay 5 seconds``, for example, 2 tabs autorotate, then 3 second passes after 2nd tab has rotated, and then if you click for example on ``tab 1``, ``tab 2`` will show not after 5 seconds, but after 2.

I tried to set an ``_after`` custom event, like this:

	 $('.foo').on("_after", function() {
	 	$(this).tabslet({
	 		delay: 5000
	 	});
	 });

But that didn't help. How do you fix that?

**Comment by vdw** [comment]
Issues with the timer (time delay) have been fixed at version 1.4.6.
