### ISSUE TITLE
I want no active tabs on load..?

### ISSUE THREAD

**Issue by DylanOpet** [vdw/Tabslet#19]
I would think there would be an option to not just have an active tab opened unless you click on it..

How would I do begin doing so? This seems like the perfect plugin just missing a very normal feature!

**Comment by vdw** [comment]
Hi, at version  [v1.4.8](https://github.com/vdw/Tabslet/blob/v1.4.8/jquery.tabslet.min.js) you can set the active option to 0 or to false in order to have all tabs inactive.
