### ISSUE TITLE
Using different HTML structure?

### ISSUE THREAD

**Issue by sirNemanjapro** [vdw/Tabslet#24]
Is it possible to use different HTML structure, so that Tabslet tabs would be outside the main div?

**Comment by vdw** [comment]
Yes it is. 
At version [v1.5.0](https://github.com/vdw/Tabslet/tree/v1.5.0) you can use the option "container" to set the id of the proper container, e.g.:

The html structure:

    <div class='tabs'>
      <ul class='horizontal'>
        <li><a href="#tab-1">Tab 1</a></li>
        <li><a href="#tab-2">Tab 2</a></li>
        <li><a href="#tab-3">Tab 3</a></li>
      </ul>
    </div>
    
    <div id='tabs_container'>
      <div id='tab-1'></div>
      <div id='tab-2'></div>
      <div id='tab-3'></div>
    </div>

The javascript:

    $('.tabs').tabslet({ container: '#tabs_container' });
