### ISSUE TITLE
Adding 'data' for attribute options

### ISSUE THREAD

**Issue by flowdee** [vdw/Tabslet#26]
Would be nice to use data attributes instead of href/alt.

**Comment by vdw** [comment]
You can by setting to the option "attribute" the value "data-something":

    $('.tabs').tabslet({
	    attribute: 'data-name'
    });

e.g.: [JSFiddle example of Tabslet with a custom attribute as selector ](https://jsfiddle.net/dkrestos/g2wwLodu/)
