### ISSUE TITLE
Navigation: Use Select or Methods

### ISSUE THREAD

**Issue by flowdee** [vdw/Tabslet#27]
For mobile devices i would like to use a select instead of a ul list to navigate the tabs.

As far as I can see right now it's not possible to use select instead of a ul list for navigation, correct? Would it be possible to add support for select fields as well? Otherwise it would be very helpful to have some small functions we can call to change the active tab.

**Comment by vdw** [comment]
You can use the following two methods from the latest version [1.6.2](https://github.com/vdw/Tabslet/tree/v1.6.2):

"next" to go to the next tab or "prev" to go to the previous tab

e.g.:

    $('.tabs').trigger('next');

**Comment by flowdee** [comment]
Mh the best case would be when I can create a select field and the select will trigger the tab.

next/prev is fine, but a select would not work with it cause it need something like "goTo".

**Comment by vdw** [comment]
You can trigger the method "show" from version [1.7.0](https://github.com/vdw/Tabslet/tree/v1.7.0) on the change of the select-field.
Note: you have to pass a parameter, the tab's identifier.

e.g.:

    $('.tabs').trigger('show', '#tab-3');

**Comment by flowdee** [comment]
Thanks for your nice work :+1:
