### ISSUE TITLE
How can I tell which Tab was clicked?

### ISSUE THREAD

**Issue by dhardy123** [vdw/Tabslet#34]
Is there a way in javascript/jquery to tell which tab was clicked?

**Comment by vdw** [comment]
Hi, you can use either *_before* or *_after* events to get the element was clicked.

    $('.tabs').on("_after", function(e) {
      alert(e.target);
    });

where *e.target* returns ```<li class="active">...</li>```

Here is an example: http://jsfiddle.net/dkrestos/Lczqrjte/
