### ISSUE TITLE
Support for external links on tabs

### ISSUE THREAD

**Issue by maciekkus** [vdw/Tabslet#35]
Hi,
It would be great if tabs could support external links. Now it seems it tries to find "div" instead of redirecting to external link.

**Comment by vdw** [comment]
Hi, 

Tabslet does **not** interfere with the default functionality of *href*s of the navigation as long as you are using the default option: ```attribute: 'href'``` (default).

Here is an example: http://jsfiddle.net/dkrestos/5d0kvet2/

Note: Use a URL (http://www.google.com) not relative paths.

**Comment by maciekkus** [comment]
Hi, You are right..
I used relative path :)
