### ISSUE TITLE
CSP violation

### ISSUE THREAD

**Issue by marxriedl** [vdw/Tabslet#37]
Hi, 

I'm getting error messages in both Firefox and Chrome due to usage of the eval() function:

Firefox (43.0.4)
`Error: call to eval() blocked by CSP`

Chrome (47.0.2526.111)
`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'".`

on line jquery.tabslet.js:130.

Thus, aborting the execution and not rendering the tabs. 

Greetings 
Markus

**Comment by vdw** [comment]
Hi, please provide the code you are using or at least, a jsfiddle example that produces that error in order to identify and solve the problem.

Thank you,
d

**Comment by marxriedl** [comment]
Hi, 

Thanks for the response, I simply tried the standard demo example. 
As far as I could determine chrome and firefox discourage the usage of the eval function thus the fail.
What confuses me though is that it seems to work for others.

Greets,
Markus

**Comment by vdw** [comment]
Try to disable the common extensions you are using on both browsers and let me know if the error remains.
