### ISSUE TITLE
Issue with deep linking

### ISSUE THREAD

**Issue by NicholasBurroughs** [vdw/Tabslet#39]
##Hey vdw, hoping you can help me out with a deep linking issue. Using the latest version, when I see deeplinking: true, nothing on the page will display. I can't even get it to work on the demo page when I download those files.

In Chrome I can see an error of "Uncaught TypeError: deep_link is not a function".

Any help would be greatly appreciated.

**Comment by vdw** [comment]
Hi, the error is resolved, please download version [1.7.2](https://github.com/vdw/Tabslet/tree/v1.7.2).

Thank you,
d

**Comment by NicholasBurroughs** [comment]
Perfect! Many thanks!
