### ISSUE TITLE
Issue with using the show method

### ISSUE THREAD

**Issue by tristanbettany** [vdw/Tabslet#45]
It seems the show method does not work due to a problem with the way the element is trying to be found. This line:

https://github.com/vdw/Tabslet/blob/master/jquery.tabslet.js#L98

if that changes from this

```
var _this = tab ? elements.find('a[' + $this.opts.attribute + '=' + tab +']').parent() : $(this);
```

to this

```
var _this = tab ? elements.find('a[' + $this.opts.attribute + '="' + tab +'"]').parent() : $(this);
```

Then It will work.... however i am not 100% sure if that change is only needed due to a version thing in jQuery. We have tried both 3.1.x and 2.2.x with the same exact problem and solution.

**Comment by vdw** [comment]
Hi, please provide a code sample or jsfiddle link where the "show" method does not work.

**Comment by jfeust** [comment]
Having the same issue.
https://jsfiddle.net/tmkyk172/

View console logs: `Uncaught Error: Syntax error, unrecognized expression: a[href=#tab-2](…)`

**Comment by vdw** [comment]
Hi, Tabslet is **not** compatible with jQuery v3.x, **yet**. We suggest you use jQuery **<= 2.1.x.**

The upcoming version 1.8 release , will be compatible with the latest jQuery.
