### ISSUE TITLE
OnPageLoad: Define active tab via html

### ISSUE THREAD

**Issue by flowdee** [vdw/Tabslet#47]
Looking for a way to define the active tab on pageload by html instead of using the "active" attribute on JS.

Is it possible right now? Couldn't fine anything. Otherwise it would be very cool to get this feature 👍

**Comment by vdw** [comment]
Hi, yes it is. You can initialize and configure Tabslet using only data attributes.

E.g.: https://jsfiddle.net/dkrestos/cyzocx7r/

**Comment by flowdee** [comment]
Perfect, thanks!
